### ISSUE TITLE
Replace favicon with blue version of Surge logo

### ISSUE THREAD

**Issue by christinaraganit** [sfusurge/surge_website#80]
## Replace favicon with the blue version of the SFU Surge logo

---

As Matthew specified in the directors' meeting on October 15, the current white favicon has low contrast when the user's browser preference is currently set to light mode. 

![image](https://github.com/user-attachments/assets/94079881-2f70-42c3-97ff-89cb3954da53)

---

Please make sure that you use the blue version of the SFU Surge logo and not the black logo as similarly, a black logo as the favicon will have low contrast for users whose browser preferences are set to dark mode.

---  

**Please reach out to the Visual Design team for the icon.** Make sure to specify the size and the file format you would like the blue version of the SFU Surge logo to be exported in.

**Comment by ChrisFong604** [comment]
Completed in https://github.com/sfusurge/surge_website/commit/8b3f07861a8d2ec1b323e9e19aad3eeb0b25c166
